package Excepciones;

public class ejercicioPracticaExcepciones3 {

public static void main(String[] args) throws Exception {
	
	int j  = 0;
	int i = 200;
	int division;
	
	division = i/j;
	
		try {
			
		}catch(Exception e){
			
		throw new Exception("Se ha oriducido un error");
		
		}
		finally {
			
			System.out.println("Final de programa");
			
		}
		
	}
	
}
